name: test
on:
  push:
    branches:
      - main
      - version-*
  pull_request:
  schedule:
    - cron: "0 13 * * *"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v8
  test:
    runs-on: ubuntu-latest
    permissions:
      # Needed for checkout
      contents: read
      # Needed for codecov OIDC token
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - run: |
          go test \
            -covermode=atomic \
            -coverprofile=${PWD}/coverage.txt \
            -json \
            ./... | tee test-output
          go tool github.com/jstemmer/go-junit-report/v2 -parser gojson -in test-output -out ${PWD}/junit.xml
      - if: ${{ always() }}
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
        with:
          paths: junit.xml
          show: "fail"
      - if: ${{ always() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        with:
          flags: authentik-${{ matrix.authentik_version }}
          use_oidc: true
      - if: ${{ always() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        with:
          flags: authentik-${{ matrix.authentik_version }}
          use_oidc: true
          report_type: test_results
